language: rust
rust:
- stable

before_script:
- cargo install cargo-expand
- rustup toolchain install nightly
- rustup component add rustfmt

script:
# Test no_features
- cargo build --verbose
- cargo test --verbose

