[package]
name = "macrotest_race_condition"
version = "0.1.0"
authors = ["emadm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macrotest = "=1.0.2"